name: AWS ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement
          json-output: true  # Enable JSON output

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Record Measurement After Setup
        id: setup-measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'Setup and Dependencies Installation'
          json-output: true  # Enable JSON output

      - name: Preprocess data
        run: python src/preprocess.py

      - name: Record Measurement After Preprocessing
        id: preprocess-measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'Data Preprocessing'
          json-output: true  # Enable JSON output

      - name: Train model
        run: python src/train_model.py

      - name: Record Measurement After Training
        id: training-measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'Model Training'
          json-output: true  # Enable JSON output

      - name: Deploy model
        run: python src/deploy_model.py

      - name: Record Measurement After Deployment
        id: deployment-measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'Model Deployment'
          json-output: true  # Enable JSON output

      - name: Display Energy Results
        id: final-measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
          json-output: true  # Enable JSON output

      - name: Save Total Energy Consumption Data
              run: echo "${{ steps.final-measurement.outputs.data-total-json }}" > total_energy_consumption.json
      
            - name: Upload Energy Consumption Artifact
              uses: actions/upload-artifact@v4
              with:
                name: total-energy-consumption
                path: total_energy_consumption.json
