name: AWS ML Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: 'python -m pip install --upgrade pip

          pip install -r requirements.txt

          '
      - id: measurement-5
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - id: setup-measurement
        name: Record Measurement After Setup
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Setup and Dependencies Installation
          task: get-measurement
      - name: Preprocess data
        run: python src/preprocess.py
      - id: measurement-8
        name: Record Measurement After Preprocess data
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Preprocess data
          task: get-measurement
      - id: preprocess-measurement
        name: Record Measurement After Preprocessing
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Data Preprocessing
          task: get-measurement
      - name: Train model
        run: python src/train_model.py
      - id: measurement-11
        name: Record Measurement After Train model
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Train model
          task: get-measurement
      - id: training-measurement
        name: Record Measurement After Training
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Model Training
          task: get-measurement
      - name: Deploy model
        run: python src/deploy_model.py
      - id: measurement-14
        name: Record Measurement After Deploy model
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Deploy model
          task: get-measurement
      - id: deployment-measurement
        name: Record Measurement After Deployment
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Model Deployment
          task: get-measurement
      - id: final-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo "${{ steps.final-measurement.outputs.data-total-json }}" > total_energy_consumption.json
      - id: measurement-18
        name: Record Measurement After Save Total Energy Consumption Data
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Save Total Energy Consumption Data
          task: get-measurement
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
      - id: final-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
